// Alternatively, we can declare members at the
//   top of the file, like so:

@members
{
    private static string ReplaceGreeting(string x)
    {
        x = x.Replace("a", "i");
        x = x.Replace("e", "i");
        x = x.Replace("o", "i");
        x = x.Replace("u", "i");
        return x;
    }
}

greeting <object>
  = x:"Hello, world!" EOF { new { Greeting = ReplaceGreeting(x) } }

EOF
  = !.
