// <auto-generated />

using System.Reflection;
using System.Runtime.InteropServices;
using System.Resources;
using System;

[assembly: AssemblyTitle("Pegasus")]
[assembly: AssemblyDescription("")]
[assembly: Guid("902d3905-d5d6-4c38-bccf-c7095c2be315")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: CLSCompliant(true)]
