// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Pegasus")]
[assembly: AssemblyDescription("")]
[assembly: Guid("902d3905-d5d6-4c38-bccf-c7095c2be315")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
