//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grammar rules were defined..
        /// </summary>
        internal static string PEG0001_ERROR_NoRulesDefined {
            get {
                return ResourceManager.GetString("PEG0001_ERROR_NoRulesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; has already been defined..
        /// </summary>
        internal static string PEG0002_ERROR_RuleAlreadyDefined {
            get {
                return ResourceManager.GetString("PEG0002_ERROR_RuleAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced rule &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PEG0003_ERROR_RuleDoesNotExist {
            get {
                return ResourceManager.GetString("PEG0003_ERROR_RuleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is left-recursive..
        /// </summary>
        internal static string PEG0004_ERROR_OBSOLETE_LeftRecursionDetected {
            get {
                return ResourceManager.GetString("PEG0004_ERROR_OBSOLETE_LeftRecursionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; has already been specified..
        /// </summary>
        internal static string PEG0005_ERROR_SettingAlreadySpecified {
            get {
                return ResourceManager.GetString("PEG0005_ERROR_SettingAlreadySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string PEG0006_WARNING_SettingUnknown {
            get {
                return ResourceManager.GetString("PEG0006_WARNING_SettingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A prefix &apos;{0}&apos; cannot be declared here because it would give a different meaning to &apos;{0}&apos; which is already declared in the current scope..
        /// </summary>
        internal static string PEG0007_ERROR_PrefixAlreadyDeclared {
            get {
                return ResourceManager.GetString("PEG0007_ERROR_PrefixAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string PEG0008_ERROR_PARSER_UnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("PEG0008_ERROR_PARSER_UnexpectedEndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal..
        /// </summary>
        internal static string PEG0009_ERROR_PARSER_UnterminatedString {
            get {
                return ResourceManager.GetString("PEG0009_ERROR_PARSER_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated character class..
        /// </summary>
        internal static string PEG0010_ERROR_PARSER_UnterminatedClass {
            get {
                return ResourceManager.GetString("PEG0010_ERROR_PARSER_UnterminatedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated code section..
        /// </summary>
        internal static string PEG0011_ERROR_PARSER_UnterminatedCode {
            get {
                return ResourceManager.GetString("PEG0011_ERROR_PARSER_UnterminatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid for the &apos;{1}&apos; setting..
        /// </summary>
        internal static string PEG0012_ERROR_SettingValueInvalid {
            get {
                return ResourceManager.GetString("PEG0012_ERROR_SettingValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flag &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string PEG0013_WARNING_FlagUnknown {
            get {
                return ResourceManager.GetString("PEG0013_WARNING_FlagUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type definition..
        /// </summary>
        internal static string PEG0014_ERROR_PARSER_InvalidType {
            get {
                return ResourceManager.GetString("PEG0014_ERROR_PARSER_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quantifier will always fail to match..
        /// </summary>
        internal static string PEG0015_WARNING_QuantifierInvalid {
            get {
                return ResourceManager.GetString("PEG0015_WARNING_QuantifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource-based literal expressions require a &apos;resources&apos; setting..
        /// </summary>
        internal static string PEG0016_ERROR_ResourcesNotSpecified {
            get {
                return ResourceManager.GetString("PEG0016_ERROR_ResourcesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is never used..
        /// </summary>
        internal static string PEG0017_WARNING_UnusedRule {
            get {
                return ResourceManager.GetString("PEG0017_WARNING_UnusedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable branch detected..
        /// </summary>
        internal static string PEG0018_WARNING_UnreachableAlternative {
            get {
                return ResourceManager.GetString("PEG0018_WARNING_UnreachableAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine a type for the rule &apos;{0}&apos;..
        /// </summary>
        internal static string PEG0019_ERROR_UnknownType {
            get {
                return ResourceManager.GetString("PEG0019_ERROR_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is left-recursive. Left-recursive rules must be memoized.  Mark this rule with the &apos;-memoize&apos; flag or eliminate the left-recursion..
        /// </summary>
        internal static string PEG0020_ERROR_UnmemoizedLeftRecursion {
            get {
                return ResourceManager.GetString("PEG0020_ERROR_UnmemoizedLeftRecursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression with no maximum repetition count will result in an infinite loop..
        /// </summary>
        internal static string PEG0021_ERROR_ZeroWidthRepetition_Certain {
            get {
                return ResourceManager.GetString("PEG0021_ERROR_ZeroWidthRepetition_Certain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression with no maximum repetition count may result in an infinite loop..
        /// </summary>
        internal static string PEG0021_WARNING_ZeroWidthRepetition_Possible {
            get {
                return ResourceManager.GetString("PEG0021_WARNING_ZeroWidthRepetition_Possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression will always result in the maximum repetition count..
        /// </summary>
        internal static string PEG0022_WARNING_ZeroWidthRepetition_Certain {
            get {
                return ResourceManager.GetString("PEG0022_WARNING_ZeroWidthRepetition_Certain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression may always result in the maximum repetition count..
        /// </summary>
        internal static string PEG0022_WARNING_ZeroWidthRepetition_Possible {
            get {
                return ResourceManager.GetString("PEG0022_WARNING_ZeroWidthRepetition_Possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is ambiguously left-recursive..
        /// </summary>
        internal static string PEG0023_ERROR_AmbiguousLeftRecursionDetected {
            get {
                return ResourceManager.GetString("PEG0023_ERROR_AmbiguousLeftRecursionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter is never used..
        /// </summary>
        internal static string PEG0024_WARNING_UnusedDelimiter {
            get {
                return ResourceManager.GetString("PEG0024_WARNING_UnusedDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is exported. Exported rule names should begin with an uppercase letter..
        /// </summary>
        internal static string PEG0025_WARNING_LowercaseExportedRule {
            get {
                return ResourceManager.GetString("PEG0025_WARNING_LowercaseExportedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is public. Public rule names should begin with an uppercase letter..
        /// </summary>
        internal static string PEG0025_WARNING_LowercasePublicRule {
            get {
                return ResourceManager.GetString("PEG0025_WARNING_LowercasePublicRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string flags &apos;{0}&apos; were unrecognized..
        /// </summary>
        internal static string PEG0026_ERROR_PARSER_StringFlagsUnrecognized {
            get {
                return ResourceManager.GetString("PEG0026_ERROR_PARSER_StringFlagsUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///    pegasus file.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
