//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string CS1026_UNEXPECTED_CHARACTER {
            get {
                return ResourceManager.GetString("CS1026_UNEXPECTED_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grammar rules were defined..
        /// </summary>
        internal static string PEG0001_NO_RULES_DEFINED {
            get {
                return ResourceManager.GetString("PEG0001_NO_RULES_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; has already been defined..
        /// </summary>
        internal static string PEG0002_RULE_ALREADY_DEFINED {
            get {
                return ResourceManager.GetString("PEG0002_RULE_ALREADY_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced rule &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PEG0003_RULE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("PEG0003_RULE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is left-recursive..
        /// </summary>
        internal static string PEG0004_LEFT_RECURSION_DETECTED {
            get {
                return ResourceManager.GetString("PEG0004_LEFT_RECURSION_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; has already been specified..
        /// </summary>
        internal static string PEG0005_SETTING_ALREADY_SPECIFIED {
            get {
                return ResourceManager.GetString("PEG0005_SETTING_ALREADY_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string PEG0006_SETTING_UNKNOWN {
            get {
                return ResourceManager.GetString("PEG0006_SETTING_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A prefix &apos;{0}&apos; cannot be declared here because it would give a different meaning to &apos;{0}&apos; which is already declared in the current scope..
        /// </summary>
        internal static string PEG0007_PREFIX_ALREADY_DECLARED {
            get {
                return ResourceManager.GetString("PEG0007_PREFIX_ALREADY_DECLARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string PEG0008_UNEXPECTED_END_OF_INPUT {
            get {
                return ResourceManager.GetString("PEG0008_UNEXPECTED_END_OF_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal..
        /// </summary>
        internal static string PEG0009_UNTERMINATED_STRING {
            get {
                return ResourceManager.GetString("PEG0009_UNTERMINATED_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated character class..
        /// </summary>
        internal static string PEG0010_UNTERMINATED_CLASS {
            get {
                return ResourceManager.GetString("PEG0010_UNTERMINATED_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated code section..
        /// </summary>
        internal static string PEG0011_UNTERMINATED_CODE {
            get {
                return ResourceManager.GetString("PEG0011_UNTERMINATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid for the &apos;{1}&apos; setting..
        /// </summary>
        internal static string PEG0012_SETTING_VALUE_INVALID {
            get {
                return ResourceManager.GetString("PEG0012_SETTING_VALUE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flag &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string PEG0013_FLAG_UNKNOWN {
            get {
                return ResourceManager.GetString("PEG0013_FLAG_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type definition..
        /// </summary>
        internal static string PEG0014_INVALID_TYPE {
            get {
                return ResourceManager.GetString("PEG0014_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quantifier will always fail to match..
        /// </summary>
        internal static string PEG0015_QUANTIFIER_INVALID {
            get {
                return ResourceManager.GetString("PEG0015_QUANTIFIER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource-based literal expressions require a &apos;resources&apos; setting..
        /// </summary>
        internal static string PEG0016_RESOURCES_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("PEG0016_RESOURCES_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is never used..
        /// </summary>
        internal static string PEG0017_UNUSED_RULE {
            get {
                return ResourceManager.GetString("PEG0017_UNUSED_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable branch detected..
        /// </summary>
        internal static string PEG0018_UNREACHABLE_ALTERNATIVE {
            get {
                return ResourceManager.GetString("PEG0018_UNREACHABLE_ALTERNATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine a type for the rule &apos;{0}&apos;..
        /// </summary>
        internal static string PEG0019_UNKNOWN_TYPE {
            get {
                return ResourceManager.GetString("PEG0019_UNKNOWN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is left-recursive. Left-recursive rules must be memoized.  Mark this rule with the &apos;-memoize&apos; flag or eliminate the left-recursion..
        /// </summary>
        internal static string PEG0020_UNMEMOIZED_LEFT_RECURSION {
            get {
                return ResourceManager.GetString("PEG0020_UNMEMOIZED_LEFT_RECURSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression with no maximum repetition count will result in an infinite loop..
        /// </summary>
        internal static string PEG0021_ZERO_WIDTH_REPETITION {
            get {
                return ResourceManager.GetString("PEG0021_ZERO_WIDTH_REPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of a zero-width expression will always result in the maximum repetition count..
        /// </summary>
        internal static string PEG0022_ZERO_WIDTH_REPETITION {
            get {
                return ResourceManager.GetString("PEG0022_ZERO_WIDTH_REPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is public. Public rule names should begin with an uppercase letter..
        /// </summary>
        internal static string PEG0023_LOWERCASE_PUBLIC_RULE {
            get {
                return ResourceManager.GetString("PEG0023_LOWERCASE_PUBLIC_RULE", resourceCulture);
            }
        }
    }
}
