// <auto-generated />
using System.Reflection;

[assembly: AssemblyProduct("Pegasus")]
[assembly: AssemblyCopyright("Copyright © 2015 John Gietzen")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: AssemblyFileVersion("4.0.0.0")]
#if !PORTABLE
[assembly: System.Runtime.InteropServices.ComVisible(false)]
#endif
