// <auto-generated />
using System.Reflection;

[assembly: AssemblyProduct("Pegasus")]
[assembly: AssemblyCopyright("Copyright © 2018 John Gietzen")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
