// <auto-generated />

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Pegasus.Tests")]
[assembly: AssemblyDescription("")]
[assembly: Guid("cdfb54b1-0863-4e3c-be89-2f98650c1a0e")]
