// -----------------------------------------------------------------------
// <copyright file="GenerateCodePass.cs" company="(none)">
//   Copyright © 2012 John Gietzen.  All Rights Reserved.
//   This source is subject to the MIT license.
//   Please see license.txt for more information.
// </copyright>
// -----------------------------------------------------------------------

namespace Pegasus.Compiler
{
    using System.CodeDom;
    using System.CodeDom.Compiler;
    using System.IO;
    using System.Reflection;
    using Pegasus.Expressions;

    internal class GenerateCodePass : CompilePass
    {
        public override void Run(Grammar grammar, CompileResult result)
        {
            using (var stringWriter = new StringWriter())
            using (var codeWriter = new IndentedTextWriter(stringWriter))
            {
                new GenerateCodeExpressionTreeWlaker(result, codeWriter).WalkGrammar(grammar);
                result.Code = stringWriter.ToString();
            }
        }

        private class GenerateCodeExpressionTreeWlaker : ExpressionTreeWalker
        {
            private readonly IndentedTextWriter code;
            private int id;
            private readonly CompileResult result;

            public GenerateCodeExpressionTreeWlaker(CompileResult result, IndentedTextWriter codeWriter)
            {
                this.result = result;
                this.code = codeWriter;
            }

            private int Id
            {
                get { return ++id; }
            }

            private string currentResultName = null;

            public override void WalkGrammar(Grammar grammar)
            {
                var assemblyName = Assembly.GetExecutingAssembly().GetName();
                this.code.WriteLine("// -----------------------------------------------------------------------");
                this.code.WriteLine("// <auto-generated>");
                this.code.WriteLine("// This code was generated by " + assemblyName.Name + " " + assemblyName.Version);
                this.code.WriteLine("//");
                this.code.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if");
                this.code.WriteLine("// the code is regenerated.");
                this.code.WriteLine("// </auto-generated>");
                this.code.WriteLine("// -----------------------------------------------------------------------");
                this.code.WriteLineNoTabs("");

                this.code.WriteLine("namespace Test");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("using System;");
                this.code.WriteLine("using System.Collections.Generic;");
                this.code.WriteLine("using Pegasus;");
                this.code.WriteLineNoTabs("");

                this.code.WriteLine("[System.CodeDom.Compiler.GeneratedCode(\"" + assemblyName.Name + "\", \"" + assemblyName.Version + "\")]");
                this.code.WriteLine("public partial class Parser");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("private Cursor rightmostErrorCursor = null;");
                this.code.WriteLine("private List<string> rightmostErrors = new List<string>();");
                this.code.WriteLineNoTabs("");

                this.code.WriteLine("public string Parse(string subject)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("var cursor = new Cursor(subject, 0);");
                this.code.WriteLine("var result = this." + grammar.Rules[0].Name + "(ref cursor);");
                this.code.WriteLine("if (result == null)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("throw new InvalidOperationException(\"Expected \" + string.Join(\", \", this.rightmostErrors) + \".\");");
                this.code.Indent--;
                this.code.WriteLine("}");
                this.code.WriteLine("return result.Value;");
                this.code.Indent--;
                this.code.WriteLine("}");

                base.WalkGrammar(grammar);

                this.code.WriteLineNoTabs("");
                this.code.WriteLine("private ParseResult<string> ParseLiteral(string literal, ref Cursor cursor)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("if (cursor.Location + literal.Length <= cursor.Subject.Length)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("var substr = cursor.Subject.Substring(cursor.Location, literal.Length);");
                this.code.WriteLine("if (substr == literal)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("var result = new ParseResult<string>(substr.Length, substr);");
                this.code.WriteLine("cursor = cursor.Advance(result);");
                this.code.WriteLine("return result;");
                this.code.Indent--;
                this.code.WriteLine("}");
                this.code.Indent--;
                this.code.WriteLine("}");
                this.code.WriteLine("this.ReportError(cursor, \"'\" + literal + \"'\");");
                this.code.WriteLine("return null;");
                this.code.Indent--;
                this.code.WriteLine("}");

                this.code.WriteLineNoTabs("");
                this.code.WriteLine("private void ReportError(Cursor cursor, string expected)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("if (this.rightmostErrorCursor != null && this.rightmostErrorCursor.Location > cursor.Location)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("return;");
                this.code.Indent--;
                this.code.WriteLine("}");
                this.code.WriteLine("if (this.rightmostErrorCursor == null || this.rightmostErrorCursor.Location < cursor.Location)");
                this.code.WriteLine("{");
                this.code.Indent++;
                this.code.WriteLine("this.rightmostErrorCursor = cursor;");
                this.code.WriteLine("this.rightmostErrors.Clear();");
                this.code.Indent--;
                this.code.WriteLine("}");
                this.code.WriteLine("this.rightmostErrors.Add(expected);");
                this.code.Indent--;
                this.code.WriteLine("}");

                this.code.Indent--;
                this.code.WriteLine("}");

                this.code.Indent--;
                this.code.WriteLine("}");
            }

            protected override void WalkRule(Rule rule)
            {
                this.code.WriteLineNoTabs("");
                this.code.WriteLine("private ParseResult<string> " + rule.Name + "(ref Cursor cursor)");
                this.code.WriteLine("{");
                this.code.Indent++;

                this.currentResultName = "r" + this.Id;
                this.code.WriteLine("ParseResult<string> " + this.currentResultName + " = null;");
                base.WalkRule(rule);
                this.code.WriteLine("return " + this.currentResultName + ";");
                this.currentResultName = null;

                this.code.Indent--;
                this.code.WriteLine("}");
            }

            protected override void WalkLiteralExpression(LiteralExpression literalExpression)
            {
                this.code.WriteLine(this.currentResultName + " = this.ParseLiteral(" + ToLiteral(literalExpression.Value) + ", ref cursor);");
            }

            protected override void WalkWildcardExpression(WildcardExpression wildcardExpression)
            {
                this.code.WriteLine(this.currentResultName + " = this.ParseAny(ref cursor);");
            }

            protected override void WalkNameExpression(NameExpression nameExpression)
            {
                this.code.WriteLine(this.currentResultName + " = this." + nameExpression.Name + "(ref cursor);");
            }

            protected override void WalkSequenceExpression(SequenceExpression sequenceExpression)
            {
                var startId = this.Id;
                this.code.WriteLine("var startCursor" + startId + " = cursor;");

                var oldResultName = this.currentResultName;

                foreach (var expression in sequenceExpression.Sequence)
                {
                    this.currentResultName = "r" + this.Id;
                    this.code.WriteLine("ParseResult<string> " + this.currentResultName + " = null;");
                    this.WalkExpression(expression);
                    this.code.WriteLine("if (" + this.currentResultName + " != null)");
                    this.code.WriteLine("{");
                    this.code.Indent++;
                }

                this.currentResultName = oldResultName;

                this.code.WriteLine("var len = cursor.Location - startCursor" + startId + ".Location;");
                this.code.WriteLine(this.currentResultName + " = new ParseResult<string>(len, cursor.Subject.Substring(startCursor" + startId + ".Location, len));");

                for (int i = 0; i < sequenceExpression.Sequence.Count; i++)
                {
                    this.code.Indent--;
                    this.code.WriteLine("}");
                    this.code.WriteLine("else");
                    this.code.WriteLine("{");
                    this.code.Indent++;
                    this.code.WriteLine("cursor = startCursor" + startId + ";");
                    this.code.Indent--;
                    this.code.WriteLine("}");
                }
            }

            protected override void WalkChoiceExpression(ChoiceExpression choiceExpression)
            {
                foreach (var expression in choiceExpression.Choices)
                {
                    this.code.WriteLine("if (" + this.currentResultName + " == null)");
                    this.code.WriteLine("{");
                    this.code.Indent++;
                    this.WalkExpression(expression);
                    this.code.Indent--;
                    this.code.WriteLine("}");
                }
            }

            private static string ToLiteral(string input)
            {
                using (var writer = new StringWriter())
                {
                    using (var provider = CodeDomProvider.CreateProvider("CSharp"))
                    {
                        provider.GenerateCodeFromExpression(new CodePrimitiveExpression(input), writer, null);
                        return writer.ToString();
                    }
                }
            }
        }
    }
}
