// <auto-generated/>

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Pegasus.Common")]
[assembly: AssemblyDescription("")]
[assembly: CLSCompliant(true)]
#if !PORTABLE
[assembly: Guid("c978cd6c-16d4-41f4-b07e-a2fbb786613c")]
#endif
