// <auto-generated/>

using System;
using System.Reflection;
using System.Resources;

[assembly: AssemblyTitle("Pegasus")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(false)]
[assembly: NeutralResourcesLanguage("en-US")]
